### PR TITLE
move action to outer loop and hub to inner loop (fixes #86)

### LINKED ISSUE #86: Action cycle does not work under USB 3.0 duality
Currently the behaviour of Action Cycle is to first cycle on USB version (3.0 for me), and then the other (2.x for me).

It should instead turn off off for all, and then turn back on for all, for the power to be actually toggled.

### PR DESCRIPTION
**Pull request by nunojpg**
This should do it.

### CODE REVIEW

File: uhubctl.c [hunk 1]
```diff
@@ -790,28 +790,30 @@ int main(int argc, char *argv[])
...
-                if (k == 1 && opt_action == POWER_OFF)
-                    continue;
+    int k; /* k=0 for power OFF, k=1 for power ON */
+    for (k=0; k<2; k++) { /* up to 2 power actions - off/on */
+        if (k == 0 && opt_action == POWER_ON )
+           continue;
+        if (k == 1 && opt_action == POWER_OFF)
+           continue;
+        if (k == 1 && opt_action == POWER_CYCLE)
+           sleep_ms(opt_delay * 1000);
```
Comment (mvp) [inline uhubctl.c]: This sleep should remain around line 849, like this:

    if (k == 0 && opt_action == POWER_CYCLE)
        sleep_ms(opt_delay * 1000);

Its debatable at what stage delay should be introduced - after power off (k==0) or just before power on (k==1).
But, I want to eventually fix some hubs slow power off (e.g. current extra wait 150ms for USB3 hubs). Proper solution would be to turn off and wait until power was actually turned off. This will need this delay sleep to happen right after, but still when k==0.

**Comment by nunojpg** [comment]
Dear @mvp, thanks. If the delay stays around line 849, then it gets called twice, the first delays the power off, the second delays the power on. This clearly is undesirable.

Another condition could be added to keep it inside the "for (i=0; i<hub_count; i++) {" loop, but as it is, the clear solution is to have it just before or just after this loop.

Please confirm how you would like me to edit the patch, even if you plan to fix this subsequent issue later with other planned changes.

Thanks again.

**Comment by mvp** [comment]
@nunojpg, it shouldn't get called twice - it will be under `if (k==0...)`. I could fix this myself in separate patch, but I wanted to make sure you get proper credit for this work.

**Comment by mvp** [comment]
Just to make it clear: move it right after `for (i=0; i<hub_count; i++)` loop.

**Comment by nunojpg** [comment]
For k==0 this code is called once for the USB2.x and once again for the USB3.0. You are placing it exactly inside the hub iteration loop, so it will be called twice. The first delays power off (because it happens between the first and second hub power off), the second delays the power on.

**Comment by mvp** [comment]
@nunojpg, I meant to move it right after the body of hub iteration loop, not inside of it.

**Comment by nunojpg** [comment]
Wilco. Initially you said to move it around line 849, where it was, and that would be inside. My comment said that it should be before or after, as you now suggest. So we agree.

**Comment by nunojpg** [comment]
I've updated it. Thanks!

**Comment by mvp** [comment]
I should have been more clear :)
Thanks a lot, this looks great!
